# Generated by Django 6.0.6 on 2026-07-11 07:19

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('acolhimento', '0015_acolhimento_chamada_classificacao'),
    ]

    operations = [
        migrations.CreateModel(
            name='Internacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('leito', models.CharField(max_length=40)),
                ('setor', models.CharField(blank=True, default='', max_length=120)),
                ('diagnostico_admissao', models.TextField(blank=True, default='')),
                ('cuidados', models.TextField(blank=True, default='')),
                ('profissional_responsavel', models.CharField(blank=True, default='', max_length=150)),
                ('observacoes', models.TextField(blank=True, default='')),
                ('status', models.CharField(choices=[('INTERNADO', 'Internado'), ('ALTA', 'Alta da Internação'), ('TRANSFERIDO', 'Transferido')], default='INTERNADO', max_length=20)),
                ('data_internacao', models.DateTimeField(default=django.utils.timezone.now)),
                ('data_alta', models.DateTimeField(blank=True, null=True)),
                ('resumo_alta', models.TextField(blank=True, default='')),
                ('profissional_alta', models.CharField(blank=True, default='', max_length=150)),
                ('acolhimento', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='internacao', to='acolhimento.acolhimento')),
            ],
            options={
                'verbose_name': 'Internação',
                'verbose_name_plural': 'Internações',
                'ordering': ['-data_internacao'],
            },
        ),
        migrations.CreateModel(
            name='EvolucaoInternacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_evolucao', models.DateTimeField(default=django.utils.timezone.now)),
                ('pressao_arterial', models.CharField(blank=True, default='', max_length=20)),
                ('temperatura', models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True)),
                ('pulso', models.PositiveIntegerField(blank=True, null=True)),
                ('frequencia_respiratoria', models.PositiveIntegerField(blank=True, null=True)),
                ('saturacao', models.PositiveIntegerField(blank=True, null=True)),
                ('evolucao', models.TextField()),
                ('conduta', models.TextField(blank=True, default='')),
                ('profissional', models.CharField(blank=True, default='', max_length=150)),
                ('internacao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evolucoes', to='internacao.internacao')),
            ],
            options={
                'verbose_name': 'Evolução da Internação',
                'verbose_name_plural': 'Evoluções da Internação',
                'ordering': ['-data_evolucao'],
            },
        ),
    ]
