# Generated by Django 6.0.6 on 2026-07-21 22:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('internacao', '0002_registros_profissionais'),
    ]

    operations = [
        migrations.CreateModel(
            name='LeitoInternacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(db_index=True, max_length=40)),
                ('tipo', models.CharField(choices=[('CLINICO', 'Clinico'), ('OBSERVACAO', 'Observacao'), ('ISOLAMENTO', 'Isolamento'), ('UTI', 'UTI'), ('OUTRO', 'Outro')], default='CLINICO', max_length=20)),
                ('status_operacional', models.CharField(choices=[('ATIVO', 'Ativo'), ('MANUTENCAO', 'Em manutencao'), ('BLOQUEADO', 'Bloqueado')], db_index=True, default='ATIVO', max_length=20)),
                ('observacao', models.CharField(blank=True, default='', max_length=180)),
                ('ordem', models.PositiveSmallIntegerField(default=0)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Leito de internacao',
                'verbose_name_plural': 'Leitos de internacao',
                'ordering': ['setor__ordem', 'ordem', 'codigo'],
            },
        ),
        migrations.CreateModel(
            name='SetorInternacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(db_index=True, max_length=40, unique=True)),
                ('nome', models.CharField(max_length=120, unique=True)),
                ('ativo', models.BooleanField(db_index=True, default=True)),
                ('ordem', models.PositiveSmallIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Setor de internacao',
                'verbose_name_plural': 'Setores de internacao',
                'ordering': ['ordem', 'nome'],
            },
        ),
        migrations.AddField(
            model_name='internacao',
            name='leito_ref',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='internacoes', to='internacao.leitointernacao', verbose_name='Leito normalizado'),
        ),
        migrations.AddField(
            model_name='leitointernacao',
            name='setor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='leitos', to='internacao.setorinternacao'),
        ),
        migrations.AddIndex(
            model_name='leitointernacao',
            index=models.Index(fields=['status_operacional', 'codigo'], name='leito_status_codigo_idx'),
        ),
        migrations.AddConstraint(
            model_name='leitointernacao',
            constraint=models.UniqueConstraint(fields=('setor', 'codigo'), name='leito_unico_por_setor'),
        ),
    ]
