# Generated by Django 6.0.6 on 2026-07-21 22:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ConselhoProfissional',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(db_index=True, max_length=50, unique=True)),
                ('nome', models.CharField(max_length=160, unique=True)),
                ('descricao', models.CharField(blank=True, default='', max_length=255)),
                ('ativo', models.BooleanField(db_index=True, default=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Conselho profissional',
                'verbose_name_plural': 'Conselhos profissionais',
                'ordering': ['nome'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='TipoVinculoTrabalho',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(db_index=True, max_length=50, unique=True)),
                ('nome', models.CharField(max_length=160, unique=True)),
                ('descricao', models.CharField(blank=True, default='', max_length=255)),
                ('ativo', models.BooleanField(db_index=True, default=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Tipo de vinculo de trabalho',
                'verbose_name_plural': 'Tipos de vinculo de trabalho',
                'ordering': ['nome'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CargoProfissional',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(db_index=True, max_length=50, unique=True)),
                ('nome', models.CharField(max_length=160, unique=True)),
                ('descricao', models.CharField(blank=True, default='', max_length=255)),
                ('ativo', models.BooleanField(db_index=True, default=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('conselho_padrao', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cargos_padrao', to='cadastros.conselhoprofissional')),
            ],
            options={
                'verbose_name': 'Cargo profissional',
                'verbose_name_plural': 'Cargos profissionais',
                'ordering': ['nome'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SetorHospitalar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(db_index=True, max_length=50, unique=True)),
                ('nome', models.CharField(max_length=160, unique=True)),
                ('descricao', models.CharField(blank=True, default='', max_length=255)),
                ('ativo', models.BooleanField(db_index=True, default=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('tipo', models.CharField(choices=[('ASSISTENCIAL', 'Assistencial'), ('ADMINISTRATIVO', 'Administrativo'), ('APOIO', 'Apoio'), ('ESTOQUE', 'Estoque'), ('OUTRO', 'Outro')], db_index=True, default='ASSISTENCIAL', max_length=20)),
            ],
            options={
                'verbose_name': 'Setor hospitalar',
                'verbose_name_plural': 'Setores hospitalares',
                'ordering': ['nome'],
                'abstract': False,
                'indexes': [models.Index(fields=['ativo', 'tipo', 'nome'], name='setor_ativo_tipo_idx')],
            },
        ),
        migrations.CreateModel(
            name='FuncaoProfissional',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(db_index=True, max_length=50, unique=True)),
                ('nome', models.CharField(max_length=160, unique=True)),
                ('descricao', models.CharField(blank=True, default='', max_length=255)),
                ('ativo', models.BooleanField(db_index=True, default=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('cargo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='funcoes', to='cadastros.cargoprofissional')),
                ('setor_padrao', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='funcoes_padrao', to='cadastros.setorhospitalar')),
            ],
            options={
                'verbose_name': 'Funcao profissional',
                'verbose_name_plural': 'Funcoes profissionais',
                'ordering': ['nome'],
                'abstract': False,
                'constraints': [models.UniqueConstraint(fields=('cargo', 'nome'), name='funcao_unica_por_cargo')],
            },
        ),
    ]
