# Generated by Django 6.0.6 on 2026-07-21 22:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ambulancia', '0002_dados_operacionais_transporte'),
        ('funcionarios', '0003_escalafuncionario_setor_ref_funcionario_cargo_ref_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='EquipamentoMedicoAmbulancia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(db_index=True, max_length=120, unique=True)),
                ('descricao', models.CharField(blank=True, default='', max_length=220)),
                ('ativo', models.BooleanField(db_index=True, default=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Equipamento medico da ambulancia',
                'verbose_name_plural': 'Equipamentos medicos da ambulancia',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='EquipamentoSolicitacaoAmbulancia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade', models.PositiveSmallIntegerField(default=1)),
                ('conferido_saida', models.BooleanField(default=False)),
                ('conferido_chegada', models.BooleanField(default=False)),
                ('observacao', models.CharField(blank=True, default='', max_length=255)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('equipamento', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='solicitacoes', to='ambulancia.equipamentomedicoambulancia')),
                ('solicitacao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='equipamentos_normalizados', to='ambulancia.solicitacaoambulancia')),
            ],
            options={
                'verbose_name': 'Equipamento da solicitacao de ambulancia',
                'verbose_name_plural': 'Equipamentos das solicitacoes de ambulancia',
                'ordering': ['solicitacao', 'equipamento__nome'],
                'constraints': [models.UniqueConstraint(fields=('solicitacao', 'equipamento'), name='amb_solic_equip_unico')],
            },
        ),
        migrations.CreateModel(
            name='MembroEquipeAmbulancia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('papel', models.CharField(choices=[('RESPONSAVEL', 'Responsavel pelo transporte'), ('MOTORISTA', 'Motorista'), ('MEDICO', 'Medico'), ('ENFERMEIRO', 'Enfermeiro'), ('TECNICO', 'Tecnico de enfermagem'), ('OUTRO', 'Outro')], db_index=True, max_length=20)),
                ('nome', models.CharField(max_length=150)),
                ('conselho', models.CharField(blank=True, default='', max_length=20)),
                ('registro', models.CharField(blank=True, default='', max_length=60)),
                ('telefone', models.CharField(blank=True, default='', max_length=30)),
                ('ordem', models.PositiveSmallIntegerField(default=0)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('funcionario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transportes_ambulancia', to='funcionarios.funcionario')),
                ('solicitacao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='equipe_normalizada', to='ambulancia.solicitacaoambulancia')),
            ],
            options={
                'verbose_name': 'Membro da equipe da ambulancia',
                'verbose_name_plural': 'Membros da equipe da ambulancia',
                'ordering': ['solicitacao', 'ordem', 'nome'],
                'indexes': [models.Index(fields=['solicitacao', 'papel'], name='amb_eq_solic_papel_idx')],
                'constraints': [models.UniqueConstraint(fields=('solicitacao', 'papel', 'nome'), name='amb_equipe_papel_nome_unico')],
            },
        ),
    ]
