# Generated by Django 6.0.6 on 2026-07-21 22:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('acolhimento', '0022_acolhimento_trava_atendimento_medico'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ManifestacaoOuvidoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('protocolo', models.CharField(blank=True, db_index=True, default='', max_length=24, unique=True)),
                ('numero_bam', models.CharField(blank=True, db_index=True, default='', max_length=20)),
                ('nome_manifestante', models.CharField(max_length=180)),
                ('cpf_manifestante', models.CharField(blank=True, db_index=True, default='', max_length=14)),
                ('telefone', models.CharField(blank=True, default='', max_length=30)),
                ('email', models.EmailField(blank=True, default='', max_length=254)),
                ('paciente_nome', models.CharField(blank=True, default='', max_length=180)),
                ('tipo', models.CharField(choices=[('RECLAMACAO', 'Reclamacao'), ('ELOGIO', 'Elogio'), ('SUGESTAO', 'Sugestao'), ('DENUNCIA', 'Denuncia'), ('INFORMACAO', 'Pedido de informacao'), ('OCORRENCIA', 'Ocorrencia'), ('OUTRO', 'Outro')], db_index=True, default='RECLAMACAO', max_length=20)),
                ('canal', models.CharField(choices=[('PRESENCIAL', 'Presencial'), ('TELEFONE', 'Telefone'), ('WHATSAPP', 'WhatsApp'), ('EMAIL', 'E-mail'), ('FORMULARIO', 'Formulario'), ('OUTRO', 'Outro')], default='PRESENCIAL', max_length=20)),
                ('prioridade', models.CharField(choices=[('BAIXA', 'Baixa'), ('NORMAL', 'Normal'), ('URGENTE', 'Urgente'), ('CRITICA', 'Critica')], db_index=True, default='NORMAL', max_length=20)),
                ('status', models.CharField(choices=[('ABERTA', 'Aberta'), ('EM_ANALISE', 'Em analise'), ('AGUARDANDO_SETOR', 'Aguardando setor'), ('RESPONDIDA', 'Respondida'), ('CONCLUIDA', 'Concluida'), ('CANCELADA', 'Cancelada')], db_index=True, default='ABERTA', max_length=30)),
                ('setor_envolvido', models.CharField(blank=True, choices=[('', '---------'), ('Acolhimento', 'Acolhimento'), ('Recepcao', 'Recepcao'), ('Classificacao', 'Classificacao'), ('Medico', 'Medico'), ('Medicacao', 'Medicacao'), ('Farmacia', 'Farmacia'), ('Laboratorio', 'Laboratorio'), ('Imagem', 'Imagem'), ('Internacao', 'Internacao'), ('Ambulancia', 'Ambulancia'), ('Almoxarifado', 'Almoxarifado'), ('Administrativo', 'Administrativo'), ('TI', 'TI'), ('Outro', 'Outro')], db_index=True, default='', max_length=80)),
                ('titulo', models.CharField(max_length=180)),
                ('relato', models.TextField()),
                ('providencias', models.TextField(blank=True, default='')),
                ('resposta', models.TextField(blank=True, default='')),
                ('observacoes_internas', models.TextField(blank=True, default='')),
                ('responsavel_nome', models.CharField(blank=True, default='', max_length=150)),
                ('responsavel_registro', models.CharField(blank=True, default='', max_length=60)),
                ('prazo_resposta', models.DateField(blank=True, db_index=True, null=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('respondido_em', models.DateTimeField(blank=True, null=True)),
                ('concluido_em', models.DateTimeField(blank=True, null=True)),
                ('aberto_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='manifestacoes_ouvidoria_abertas', to=settings.AUTH_USER_MODEL)),
                ('acolhimento', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='manifestacoes_ouvidoria', to='acolhimento.acolhimento')),
            ],
            options={
                'verbose_name': 'Manifestacao de ouvidoria',
                'verbose_name_plural': 'Manifestacoes de ouvidoria',
                'ordering': ['-criado_em'],
            },
        ),
        migrations.CreateModel(
            name='AndamentoOuvidoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(blank=True, choices=[('ABERTA', 'Aberta'), ('EM_ANALISE', 'Em analise'), ('AGUARDANDO_SETOR', 'Aguardando setor'), ('RESPONDIDA', 'Respondida'), ('CONCLUIDA', 'Concluida'), ('CANCELADA', 'Cancelada')], default='', max_length=30)),
                ('anotacao', models.TextField()),
                ('profissional_nome', models.CharField(blank=True, default='', max_length=150)),
                ('profissional_registro', models.CharField(blank=True, default='', max_length=60)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('criado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='andamentos_ouvidoria', to=settings.AUTH_USER_MODEL)),
                ('manifestacao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='andamentos', to='ouvidoria.manifestacaoouvidoria')),
            ],
            options={
                'verbose_name': 'Andamento de ouvidoria',
                'verbose_name_plural': 'Andamentos de ouvidoria',
                'ordering': ['-criado_em'],
            },
        ),
        migrations.AddIndex(
            model_name='manifestacaoouvidoria',
            index=models.Index(fields=['status', 'prioridade', 'criado_em'], name='ouv_status_prio_dt_idx'),
        ),
        migrations.AddIndex(
            model_name='manifestacaoouvidoria',
            index=models.Index(fields=['setor_envolvido', 'status'], name='ouv_setor_status_idx'),
        ),
        migrations.AddIndex(
            model_name='manifestacaoouvidoria',
            index=models.Index(fields=['prazo_resposta', 'status'], name='ouv_prazo_status_idx'),
        ),
        migrations.AddIndex(
            model_name='manifestacaoouvidoria',
            index=models.Index(fields=['tipo', 'criado_em'], name='ouv_tipo_dt_idx'),
        ),
        migrations.AddIndex(
            model_name='andamentoouvidoria',
            index=models.Index(fields=['manifestacao', 'criado_em'], name='ouv_and_manif_dt_idx'),
        ),
    ]
