# Generated by Django 6.0.6 on 2026-07-21 22:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0001_initial'),
        ('funcionarios', '0002_data_demissao_vinculos'),
    ]

    operations = [
        migrations.AddField(
            model_name='escalafuncionario',
            name='setor_ref',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='escalas_funcionarios', to='cadastros.setorhospitalar', verbose_name='Setor normalizado'),
        ),
        migrations.AddField(
            model_name='funcionario',
            name='cargo_ref',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='funcionarios', to='cadastros.cargoprofissional', verbose_name='Cargo normalizado'),
        ),
        migrations.AddField(
            model_name='funcionario',
            name='conselho_ref',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='funcionarios', to='cadastros.conselhoprofissional', verbose_name='Conselho normalizado'),
        ),
        migrations.AddField(
            model_name='funcionario',
            name='funcao_ref',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='funcionarios', to='cadastros.funcaoprofissional', verbose_name='Funcao normalizada'),
        ),
        migrations.AddField(
            model_name='funcionario',
            name='setor_ref',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='funcionarios', to='cadastros.setorhospitalar', verbose_name='Setor normalizado'),
        ),
        migrations.AddField(
            model_name='funcionario',
            name='tipo_vinculo_ref',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='funcionarios', to='cadastros.tipovinculotrabalho', verbose_name='Tipo de vinculo normalizado'),
        ),
        migrations.AddField(
            model_name='vinculofuncionario',
            name='cargo_ref',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vinculos_funcionarios', to='cadastros.cargoprofissional', verbose_name='Cargo normalizado'),
        ),
        migrations.AddField(
            model_name='vinculofuncionario',
            name='setor_ref',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vinculos_funcionarios', to='cadastros.setorhospitalar', verbose_name='Setor normalizado'),
        ),
        migrations.AddField(
            model_name='vinculofuncionario',
            name='tipo_vinculo_ref',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vinculos_funcionarios', to='cadastros.tipovinculotrabalho', verbose_name='Tipo de vinculo normalizado'),
        ),
    ]
