# Generated by Django 6.0.6 on 2026-07-14 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('painel', '0002_chamadapainel_tipo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chamadapainel',
            name='tipo',
            field=models.CharField(choices=[('CHAMADA', 'Chamada'), ('AUSENCIA', 'Ausencia'), ('RETORNO', 'Retorno para fila')], default='CHAMADA', max_length=20),
        ),
    ]
