# Generated by Django 6.0.6 on 2026-07-17 07:38

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acolhimento', '0018_acolhimento_acolh_status_data_idx_and_more'),
        ('painel', '0003_alter_chamadapainel_tipo'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='chamadapainel',
            index=models.Index(fields=['setor', 'criado_em'], name='chamada_setor_dt_idx'),
        ),
        migrations.AddIndex(
            model_name='chamadapainel',
            index=models.Index(fields=['acolhimento', 'setor', 'tipo'], name='chamada_acolh_set_idx'),
        ),
    ]
