# Generated by Django 6.0.6 on 2026-07-21 22:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_alter_painelsistema_codigo'),
        ('cadastros', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='cargo_ref',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='usuarios', to='cadastros.cargoprofissional', verbose_name='Cargo normalizado'),
        ),
        migrations.AddField(
            model_name='usuario',
            name='conselho_ref',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='usuarios', to='cadastros.conselhoprofissional', verbose_name='Conselho normalizado'),
        ),
        migrations.AddField(
            model_name='usuario',
            name='funcao_ref',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='usuarios', to='cadastros.funcaoprofissional', verbose_name='Funcao normalizada'),
        ),
    ]
