# Generated by Django 6.0.6 on 2026-07-04 17:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('acolhimento', '0010_alter_acolhimento_options_alter_acolhimento_cpf_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConsultaMedica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('medico_responsavel', models.CharField(max_length=150)),
                ('queixa_principal', models.TextField()),
                ('historia_doenca_atual', models.TextField(blank=True)),
                ('exame_fisico', models.TextField(blank=True)),
                ('hipotese_diagnostica', models.TextField()),
                ('cid', models.CharField(blank=True, max_length=20)),
                ('conduta', models.CharField(choices=[('ALTA', 'Alta Médica'), ('OBSERVACAO', 'Observação'), ('INTERNACAO', 'Internação'), ('ENCAMINHAMENTO', 'Encaminhamento')], max_length=30)),
                ('prescricao', models.TextField(blank=True)),
                ('orientacoes', models.TextField(blank=True)),
                ('data_consulta', models.DateTimeField(auto_now_add=True)),
                ('acolhimento', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='consulta_medica', to='acolhimento.acolhimento')),
            ],
            options={
                'verbose_name': 'Consulta Médica',
                'verbose_name_plural': 'Consultas Médicas',
                'ordering': ['-data_consulta'],
            },
        ),
    ]
