# Generated by Django 6.0.6 on 2026-07-04 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medico', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CID',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(db_index=True, max_length=10, unique=True)),
                ('descricao', models.CharField(db_index=True, max_length=255)),
            ],
            options={
                'verbose_name': 'CID',
                'verbose_name_plural': 'CIDs',
                'ordering': ['codigo'],
            },
        ),
    ]
