# Generated by Django 6.0.6 on 2026-07-04 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medico', '0002_cid'),
    ]

    operations = [
        migrations.AddField(
            model_name='cid',
            name='tipo',
            field=models.CharField(choices=[('GRUPO', 'Grupo'), ('CATEGORIA', 'Categoria'), ('SUBCATEGORIA', 'Subcategoria')], default='CATEGORIA', max_length=20),
        ),
        migrations.AlterField(
            model_name='cid',
            name='codigo',
            field=models.CharField(db_index=True, max_length=20, unique=True),
        ),
    ]
