# Generated by Django 6.0.6 on 2026-07-04 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medico', '0003_cid_tipo_alter_cid_codigo'),
    ]

    operations = [
        migrations.AddField(
            model_name='consultamedica',
            name='exames_laboratoriais',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='cid',
            name='tipo',
            field=models.CharField(choices=[('CAPITULO', 'Capítulo'), ('GRUPO', 'Grupo'), ('CATEGORIA', 'Categoria'), ('SUBCATEGORIA', 'Subcategoria')], default='SUBCATEGORIA', max_length=20),
        ),
    ]
