# Generated by Django 6.0.6 on 2026-07-04 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medico', '0004_consultamedica_exames_laboratoriais_alter_cid_tipo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consultamedica',
            name='conduta',
            field=models.CharField(choices=[('ALTA', 'Alta Médica'), ('MEDICACAO', 'Medicação'), ('EXAMES_LAB', 'Exames Laboratoriais'), ('EXAMES_IMAGEM', 'Exames de Imagem'), ('OBSERVACAO', 'Observação'), ('INTERNACAO', 'Internação'), ('ENCAMINHAMENTO', 'Encaminhamento')], max_length=30),
        ),
    ]
