# Generated by Django 6.0.6 on 2026-07-04 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medico', '0005_alter_consultamedica_conduta'),
    ]

    operations = [
        migrations.AddField(
            model_name='consultamedica',
            name='exames_imagem',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='consultamedica',
            name='cid',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='consultamedica',
            name='exame_fisico',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='consultamedica',
            name='exames_laboratoriais',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='consultamedica',
            name='historia_doenca_atual',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='consultamedica',
            name='orientacoes',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='consultamedica',
            name='prescricao',
            field=models.TextField(blank=True, default=''),
        ),
    ]
