# Generated by Django 6.0.6 on 2026-07-04 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medico', '0006_consultamedica_exames_imagem_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='consultamedica',
            name='solicita_exames_imagem',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='consultamedica',
            name='solicita_exames_laboratoriais',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='consultamedica',
            name='solicita_medicacao',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='consultamedica',
            name='conduta',
            field=models.CharField(choices=[('RETORNO', 'Retorno após procedimentos'), ('ALTA', 'Alta Médica'), ('OBSERVACAO', 'Observação'), ('INTERNACAO', 'Internação'), ('ENCAMINHAMENTO', 'Encaminhamento')], max_length=30),
        ),
    ]
