# Generated by Django 6.0.6 on 2026-07-04 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medico', '0007_consultamedica_solicita_exames_imagem_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='consultamedica',
            name='exames_imagem_realizados',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='consultamedica',
            name='exames_laboratoriais_realizados',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='consultamedica',
            name='medicacao_realizada',
            field=models.BooleanField(default=False),
        ),
    ]
