# Generated by Django 6.0.6 on 2026-07-05 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medico', '0008_consultamedica_exames_imagem_realizados_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='consultamedica',
            name='data_resultado_imagem',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='consultamedica',
            name='data_resultado_laboratorio',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='consultamedica',
            name='resultado_exames_imagem',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='consultamedica',
            name='resultado_exames_laboratoriais',
            field=models.TextField(blank=True, default=''),
        ),
    ]
