# Generated by Django 6.0.6 on 2026-07-05 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medico', '0009_consultamedica_data_resultado_imagem_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='consultamedica',
            name='tecnico_imagem_nome',
            field=models.CharField(blank=True, default='', max_length=150),
        ),
        migrations.AddField(
            model_name='consultamedica',
            name='tecnico_imagem_registro',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AddField(
            model_name='consultamedica',
            name='tecnico_laboratorio_nome',
            field=models.CharField(blank=True, default='', max_length=150),
        ),
        migrations.AddField(
            model_name='consultamedica',
            name='tecnico_laboratorio_registro',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
    ]
