# Generated by Django 6.0.6 on 2026-07-05 21:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medico', '0010_consultamedica_tecnico_imagem_nome_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='consultamedica',
            name='tecnico_densitometria_nome',
            field=models.CharField(blank=True, default='', max_length=150),
        ),
        migrations.AddField(
            model_name='consultamedica',
            name='tecnico_densitometria_registro',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AddField(
            model_name='consultamedica',
            name='tecnico_mamografia_nome',
            field=models.CharField(blank=True, default='', max_length=150),
        ),
        migrations.AddField(
            model_name='consultamedica',
            name='tecnico_mamografia_registro',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AddField(
            model_name='consultamedica',
            name='tecnico_raiox_nome',
            field=models.CharField(blank=True, default='', max_length=150),
        ),
        migrations.AddField(
            model_name='consultamedica',
            name='tecnico_raiox_registro',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AddField(
            model_name='consultamedica',
            name='tecnico_tomografia_nome',
            field=models.CharField(blank=True, default='', max_length=150),
        ),
        migrations.AddField(
            model_name='consultamedica',
            name='tecnico_tomografia_registro',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
    ]
