# Generated by Django 6.0.6 on 2026-07-05 22:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medico', '0011_consultamedica_tecnico_densitometria_nome_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='consultamedica',
            name='data_resultado_densitometria',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='consultamedica',
            name='data_resultado_mamografia',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='consultamedica',
            name='data_resultado_raiox',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='consultamedica',
            name='data_resultado_tomografia',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='consultamedica',
            name='densitometria_realizada',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='consultamedica',
            name='mamografia_realizada',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='consultamedica',
            name='raiox_realizado',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='consultamedica',
            name='resultado_densitometria',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='consultamedica',
            name='resultado_mamografia',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='consultamedica',
            name='resultado_raiox',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='consultamedica',
            name='resultado_tomografia',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='consultamedica',
            name='tomografia_realizada',
            field=models.BooleanField(default=False),
        ),
    ]
