# Generated by Django 6.0.6 on 2026-07-05 23:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medico', '0012_consultamedica_data_resultado_densitometria_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='consultamedica',
            old_name='tecnico_imagem_nome',
            new_name='profissional_medicacao_nome',
        ),
        migrations.RenameField(
            model_name='consultamedica',
            old_name='tecnico_imagem_registro',
            new_name='profissional_medicacao_registro',
        ),
        migrations.AddField(
            model_name='consultamedica',
            name='data_medicacao',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='consultamedica',
            name='medicacao_administrada',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='consultamedica',
            name='observacoes_medicacao',
            field=models.TextField(blank=True, default=''),
        ),
    ]
