# Generated by Django 6.0.6 on 2026-07-05 23:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medico', '0013_rename_tecnico_imagem_nome_consultamedica_profissional_medicacao_nome_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='consultamedica',
            name='dose_medicacao',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='consultamedica',
            name='horario_medicacao',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='consultamedica',
            name='lote_medicacao',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='consultamedica',
            name='materiais_utilizados_medicacao',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='consultamedica',
            name='medicamento_utilizado',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='consultamedica',
            name='quantidade_medicacao',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='consultamedica',
            name='via_medicacao',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
