# Generated by Django 6.0.6 on 2026-07-06 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medico', '0014_consultamedica_dose_medicacao_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='consultamedica',
            name='indicacao_outros_imagem',
            field=models.TextField(blank=True, null=True, verbose_name='Indicação clínica de outros exames de imagem'),
        ),
        migrations.AddField(
            model_name='consultamedica',
            name='indicacao_raiox',
            field=models.TextField(blank=True, null=True, verbose_name='Indicação clínica do Raio-X'),
        ),
        migrations.AddField(
            model_name='consultamedica',
            name='indicacao_tomografia',
            field=models.TextField(blank=True, null=True, verbose_name='Indicação clínica da Tomografia'),
        ),
    ]
