# Generated by Django 6.0.6 on 2026-07-08 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medico', '0015_consultamedica_indicacao_outros_imagem_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='consultamedica',
            name='data_liberacao_farmacia',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='consultamedica',
            name='farmacia_liberada',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='consultamedica',
            name='lote_farmacia',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='consultamedica',
            name='medicamentos_dispensados',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='consultamedica',
            name='observacao_farmacia',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='consultamedica',
            name='profissional_farmacia_nome',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='consultamedica',
            name='profissional_farmacia_registro',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
        migrations.AddField(
            model_name='consultamedica',
            name='quantidade_farmacia',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='consultamedica',
            name='validade_farmacia',
            field=models.DateField(blank=True, null=True),
        ),
    ]
