# Generated by Django 6.0.6 on 2026-07-08 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medico', '0016_consultamedica_data_liberacao_farmacia_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='consultamedica',
            name='crm_medico',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='CRM do médico'),
        ),
    ]
