# Generated by Django 6.0.6 on 2026-07-11 17:23

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medico', '0017_consultamedica_crm_medico'),
    ]

    operations = [
        migrations.CreateModel(
            name='TransferenciaConsultaMedica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('medico_anterior', models.CharField(blank=True, default='', max_length=150)),
                ('crm_anterior', models.CharField(blank=True, default='', max_length=30)),
                ('medico_novo', models.CharField(max_length=150)),
                ('crm_novo', models.CharField(blank=True, default='', max_length=30)),
                ('motivo', models.CharField(choices=[('PLANTAO', 'Passagem de plantão'), ('TRANSFERENCIA', 'Transferência do paciente'), ('AUSENCIA', 'Saída ou ausência do médico'), ('OUTRO', 'Outro motivo')], default='PLANTAO', max_length=30)),
                ('observacao', models.TextField(blank=True, default='')),
                ('data_transferencia', models.DateTimeField(default=django.utils.timezone.now)),
                ('consulta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transferencias_medico', to='medico.consultamedica')),
            ],
            options={
                'verbose_name': 'Transferência de médico',
                'verbose_name_plural': 'Transferências de médico',
                'ordering': ['-data_transferencia'],
            },
        ),
    ]
