# Generated by Django 6.0.6 on 2026-07-17 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acolhimento', '0018_acolhimento_acolh_status_data_idx_and_more'),
        ('medico', '0018_transferenciaconsultamedica'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='consultamedica',
            index=models.Index(fields=['data_consulta'], name='consulta_data_idx'),
        ),
        migrations.AddIndex(
            model_name='consultamedica',
            index=models.Index(fields=['medico_responsavel', 'data_consulta'], name='consulta_medico_idx'),
        ),
        migrations.AddIndex(
            model_name='consultamedica',
            index=models.Index(fields=['solicita_medicacao', 'farmacia_liberada', 'medicacao_realizada', 'data_consulta'], name='consulta_medic_idx'),
        ),
        migrations.AddIndex(
            model_name='consultamedica',
            index=models.Index(fields=['solicita_exames_laboratoriais', 'exames_laboratoriais_realizados', 'data_consulta'], name='consulta_lab_idx'),
        ),
        migrations.AddIndex(
            model_name='consultamedica',
            index=models.Index(fields=['solicita_exames_imagem', 'data_consulta'], name='consulta_img_idx'),
        ),
    ]
