# Generated by Django 6.0.6 on 2026-07-17 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medico', '0019_consultamedica_consulta_data_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='consultamedica',
            name='atestado',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='consultamedica',
            name='receita',
            field=models.TextField(blank=True, default=''),
        ),
    ]
