# Generated by Django 6.0.6 on 2026-07-17 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medico', '0020_consultamedica_atestado_consultamedica_receita'),
    ]

    operations = [
        migrations.AddField(
            model_name='consultamedica',
            name='atestado_cid',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AddField(
            model_name='consultamedica',
            name='atestado_dias',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
    ]
