# Generated by Django 6.0.6 on 2026-07-18 02:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medico', '0021_consultamedica_atestado_cid_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReavaliacaoMedica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('medico_responsavel', models.CharField(max_length=150)),
                ('crm_medico', models.CharField(blank=True, default='', max_length=30)),
                ('cid', models.CharField(blank=True, default='', max_length=20)),
                ('avaliacao', models.TextField()),
                ('conduta', models.CharField(choices=[('RETORNO', 'Retorno após procedimentos'), ('ALTA', 'Alta Médica'), ('OBSERVACAO', 'Observação'), ('INTERNACAO', 'Internação'), ('ENCAMINHAMENTO', 'Encaminhamento')], max_length=30)),
                ('orientacoes', models.TextField(blank=True, default='')),
                ('data_reavaliacao', models.DateTimeField(auto_now_add=True)),
                ('consulta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reavaliacoes', to='medico.consultamedica')),
            ],
            options={
                'verbose_name': 'Reavaliacao medica',
                'verbose_name_plural': 'Reavaliacoes medicas',
                'ordering': ['-data_reavaliacao'],
                'indexes': [models.Index(fields=['consulta', 'data_reavaliacao'], name='reav_consulta_dt_idx'), models.Index(fields=['medico_responsavel', 'data_reavaliacao'], name='reav_medico_dt_idx')],
            },
        ),
    ]
