# Generated by Django 6.0.6 on 2026-07-21 22:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medico', '0022_reavaliacaomedica'),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentoConsultaMedica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('PRESCRICAO', 'Prescricao medica'), ('RECEITA', 'Receita medica'), ('ATESTADO', 'Atestado medico'), ('ORIENTACAO', 'Orientacoes ao paciente')], db_index=True, max_length=20)),
                ('texto', models.TextField(blank=True, default='')),
                ('dias_atestado', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('cid_codigo', models.CharField(blank=True, default='', max_length=20)),
                ('profissional_nome', models.CharField(blank=True, default='', max_length=150)),
                ('profissional_registro', models.CharField(blank=True, default='', max_length=60)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('cid', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='documentos_consulta', to='medico.cid')),
                ('consulta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documentos_clinicos', to='medico.consultamedica')),
            ],
            options={
                'verbose_name': 'Documento da consulta medica',
                'verbose_name_plural': 'Documentos da consulta medica',
                'ordering': ['consulta', 'tipo'],
                'indexes': [models.Index(fields=['tipo', 'atualizado_em'], name='doc_tipo_dt_idx'), models.Index(fields=['cid_codigo'], name='doc_cid_codigo_idx')],
                'constraints': [models.UniqueConstraint(fields=('consulta', 'tipo'), name='doc_consulta_tipo_unico')],
            },
        ),
    ]
