# Generated by Django 6.0.6 on 2026-06-19 19:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('acolhimento', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Recepcao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_ficha', models.CharField(max_length=20, unique=True)),
                ('observacao', models.TextField(blank=True, null=True)),
                ('data_recepcao', models.DateTimeField(auto_now_add=True)),
                ('acolhimento', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='recepcao', to='acolhimento.acolhimento')),
            ],
            options={
                'verbose_name': 'Recepção',
                'verbose_name_plural': 'Recepções',
            },
        ),
    ]
