# Generated by Django 6.0.6 on 2026-06-21 17:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recepcao', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Recepcao',
        ),
    ]
