# Generated by Django 6.0.6 on 2026-06-28 01:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('recepcao', '0002_delete_recepcao'),
    ]

    operations = [
        migrations.CreateModel(
            name='Recepcao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_completo', models.CharField(max_length=200)),
                ('nome_social', models.CharField(blank=True, max_length=200, null=True)),
                ('cpf', models.CharField(max_length=14, unique=True)),
                ('cns', models.CharField(blank=True, max_length=20, null=True, verbose_name='Cartão Nacional de Saúde')),
                ('sexo', models.CharField(choices=[('M', 'Masculino'), ('F', 'Feminino'), ('O', 'Outro')], max_length=1)),
                ('raca_cor', models.CharField(choices=[('Branca', 'Branca'), ('Preta', 'Preta'), ('Parda', 'Parda'), ('Amarela', 'Amarela'), ('Indígena', 'Indígena'), ('Não Informado', 'Não Informado')], max_length=20)),
                ('nascimento', models.DateField()),
                ('idade', models.PositiveIntegerField()),
                ('nacionalidade', models.CharField(max_length=100)),
                ('uf_nascimento', models.CharField(max_length=2, verbose_name='UF de nascimento')),
                ('naturalidade', models.CharField(max_length=100, verbose_name='Cidade de nascimento')),
                ('nome_mae', models.CharField(max_length=200)),
                ('nome_pai', models.CharField(blank=True, max_length=200, null=True)),
                ('telefone', models.CharField(max_length=20)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('situacao_rua', models.BooleanField(default=False)),
                ('cep', models.CharField(max_length=9)),
                ('municipio', models.CharField(max_length=100)),
                ('bairro', models.CharField(max_length=100)),
                ('logradouro', models.CharField(max_length=200)),
                ('numero', models.CharField(max_length=10)),
                ('complemento', models.CharField(blank=True, max_length=100, null=True)),
                ('nome_responsavel', models.CharField(blank=True, max_length=200, null=True)),
                ('cpf_responsavel', models.CharField(blank=True, max_length=14, null=True)),
                ('nacionalidade_responsavel', models.CharField(blank=True, max_length=100, null=True)),
                ('uf_nascimento_responsavel', models.CharField(blank=True, max_length=2, null=True)),
                ('naturalidade_responsavel', models.CharField(blank=True, max_length=100, null=True)),
                ('data_cadastro', models.DateTimeField(auto_now_add=True)),
                ('data_atualizacao', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Recepção',
                'verbose_name_plural': 'Recepções',
                'ordering': ['nome_completo'],
            },
        ),
    ]
