# Generated by Django 6.0.6 on 2026-06-28 23:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recepcao', '0003_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recepcao',
            name='nacionalidade',
            field=models.CharField(choices=[('Brasileira', 'Brasileira'), ('Estrangeira', 'Estrangeira')], max_length=20),
        ),
        migrations.AlterField(
            model_name='recepcao',
            name='nacionalidade_responsavel',
            field=models.CharField(blank=True, choices=[('Brasileira', 'Brasileira'), ('Estrangeira', 'Estrangeira')], max_length=20, null=True),
        ),
    ]
