# Generated by Django 6.0.6 on 2026-06-29 00:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recepcao', '0004_alter_recepcao_nacionalidade_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recepcao',
            name='naturalidade',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Cidade de nascimento'),
        ),
        migrations.AlterField(
            model_name='recepcao',
            name='uf_nascimento',
            field=models.CharField(blank=True, max_length=2, null=True, verbose_name='UF de nascimento'),
        ),
    ]
