# Generated by Django 6.0.6 on 2026-07-04 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recepcao', '0007_recepcao_uf_nascimento_responsavel_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recepcao',
            name='cns',
            field=models.CharField(blank=True, max_length=18, null=True, verbose_name='Cartão Nacional de Saúde'),
        ),
    ]
