# Generated by Django 6.0.6 on 2026-06-13 01:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Acolhimento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_paciente', models.CharField(max_length=200)),
                ('cpf', models.CharField(blank=True, max_length=14, null=True)),
                ('data_nascimento', models.DateField()),
                ('idade', models.PositiveIntegerField(blank=True, null=True)),
                ('pressao_arterial', models.CharField(blank=True, max_length=20, null=True, verbose_name='PA')),
                ('temperatura', models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True)),
                ('frequencia_respiratoria', models.PositiveIntegerField(blank=True, null=True, verbose_name='FR')),
                ('pulso', models.PositiveIntegerField(blank=True, null=True)),
                ('dor', models.PositiveIntegerField(blank=True, null=True)),
                ('tipo_atendimento', models.CharField(choices=[('NORMAL', 'Atendimento Normal'), ('RISCO', 'Risco'), ('PREFERENCIAL', 'Atendimento Preferencial')], max_length=20)),
                ('data_acolhimento', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Acolhimento',
                'verbose_name_plural': 'Acolhimentos',
                'ordering': ['-data_acolhimento'],
            },
        ),
    ]
