# Generated by Django 6.0.6 on 2026-06-21 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acolhimento', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='acolhimento',
            name='numero_bam',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Nº BAM'),
        ),
    ]
