# Generated by Django 6.0.6 on 2026-06-21 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acolhimento', '0002_acolhimento_numero_bam'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='acolhimento',
            options={'ordering': ['-data_acolhimento']},
        ),
        migrations.AlterField(
            model_name='acolhimento',
            name='frequencia_respiratoria',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='acolhimento',
            name='numero_bam',
            field=models.PositiveIntegerField(blank=True, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='acolhimento',
            name='pressao_arterial',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
