# Generated by Django 6.0.6 on 2026-06-21 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acolhimento', '0003_alter_acolhimento_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='acolhimento',
            options={'ordering': ['-data_acolhimento'], 'verbose_name': 'Acolhimento', 'verbose_name_plural': 'Acolhimentos'},
        ),
        migrations.AlterField(
            model_name='acolhimento',
            name='frequencia_respiratoria',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='FR'),
        ),
        migrations.AlterField(
            model_name='acolhimento',
            name='numero_bam',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Nº BAM'),
        ),
        migrations.AlterField(
            model_name='acolhimento',
            name='pressao_arterial',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='PA'),
        ),
    ]
