# Generated by Django 6.0.6 on 2026-06-21 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acolhimento', '0004_alter_acolhimento_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='acolhimento',
            options={},
        ),
        migrations.AlterField(
            model_name='acolhimento',
            name='frequencia_respiratoria',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='acolhimento',
            name='pressao_arterial',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
