# Generated by Django 6.0.6 on 2026-06-22 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acolhimento', '0005_alter_acolhimento_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='acolhimento',
            name='numero_bam',
            field=models.CharField(blank=True, db_index=True, max_length=20, null=True, unique=True, verbose_name='Nº BAM'),
        ),
    ]
