# Generated by Django 6.0.6 on 2026-06-22 21:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('acolhimento', '0006_alter_acolhimento_numero_bam'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='acolhimento',
            options={'ordering': ['-data_acolhimento']},
        ),
    ]
