# Generated by Django 6.0.6 on 2026-06-28 02:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acolhimento', '0007_alter_acolhimento_options'),
        ('recepcao', '0003_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='acolhimento',
            name='paciente',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='acolhimentos', to='recepcao.recepcao'),
        ),
    ]
