# Generated by Django 6.0.6 on 2026-06-28 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acolhimento', '0008_acolhimento_paciente'),
    ]

    operations = [
        migrations.AddField(
            model_name='acolhimento',
            name='status',
            field=models.CharField(choices=[('RECEPCAO', 'Aguardando Recepção'), ('CLASSIFICACAO', 'Aguardando Classificação'), ('CONSULTA', 'Aguardando Consulta'), ('FINALIZADO', 'Finalizado')], default='RECEPCAO', max_length=20),
        ),
    ]
