# Generated by Django 6.0.6 on 2026-07-02 07:26

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acolhimento', '0009_acolhimento_status'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='acolhimento',
            options={'ordering': ['-data_acolhimento'], 'verbose_name': 'Acolhimento', 'verbose_name_plural': 'Acolhimentos'},
        ),
        migrations.AlterField(
            model_name='acolhimento',
            name='cpf',
            field=models.CharField(blank=True, db_index=True, max_length=14, null=True),
        ),
        migrations.AlterField(
            model_name='acolhimento',
            name='dor',
            field=models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)]),
        ),
        migrations.AlterField(
            model_name='acolhimento',
            name='idade',
            field=models.PositiveIntegerField(blank=True, editable=False, null=True),
        ),
    ]
