# Generated by Django 6.0.6 on 2026-07-04 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acolhimento', '0011_alter_acolhimento_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='acolhimento',
            name='status',
            field=models.CharField(choices=[('RECEPCAO', 'Aguardando Recepção'), ('CLASSIFICACAO', 'Aguardando Classificação'), ('CONSULTA', 'Aguardando Consulta'), ('MEDICACAO', 'Aguardando Medicação'), ('EXAMES_LAB', 'Aguardando Exames Laboratoriais'), ('EXAMES_IMAGEM', 'Aguardando Exames de Imagem'), ('RETORNO_MEDICO', 'Retorno ao Médico'), ('OBSERVACAO', 'Em Observação'), ('INTERNACAO', 'Internação'), ('FINALIZADO', 'Finalizado')], default='RECEPCAO', max_length=20),
        ),
    ]
