# Generated by Django 6.0.6 on 2026-07-09 20:58

import acolhimento.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acolhimento', '0013_alter_acolhimento_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='acolhimento',
            name='hora_chegada',
            field=models.TimeField(blank=True, default=acolhimento.models.hora_atual, null=True, verbose_name='Hora da chegada'),
        ),
    ]
