# Generated by Django 6.0.6 on 2026-07-14 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acolhimento', '0015_acolhimento_chamada_classificacao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='acolhimento',
            name='status',
            field=models.CharField(choices=[('RECEPCAO', 'Aguardando Recepção'), ('CLASSIFICACAO', 'Aguardando Classificação'), ('CONSULTA', 'Aguardando Consulta'), ('PROCEDIMENTOS', 'Aguardando Procedimentos'), ('RETORNO_MEDICO', 'Retorno ao Médico'), ('OBSERVACAO', 'Em Observação'), ('INTERNACAO', 'Internação'), ('AUSENTE', 'Ausente'), ('FINALIZADO', 'Finalizado')], default='RECEPCAO', max_length=20),
        ),
    ]
