# Generated by Django 6.0.6 on 2026-07-14 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acolhimento', '0016_alter_acolhimento_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='acolhimento',
            name='data_ausente',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Data da ausÃªncia'),
        ),
        migrations.AddField(
            model_name='acolhimento',
            name='status_antes_ausencia',
            field=models.CharField(blank=True, choices=[('RECEPCAO', 'Aguardando Recepção'), ('CLASSIFICACAO', 'Aguardando Classificação'), ('CONSULTA', 'Aguardando Consulta'), ('PROCEDIMENTOS', 'Aguardando Procedimentos'), ('RETORNO_MEDICO', 'Retorno ao Médico'), ('OBSERVACAO', 'Em Observação'), ('INTERNACAO', 'Internação'), ('AUSENTE', 'Ausente'), ('FINALIZADO', 'Finalizado')], default='', max_length=20, verbose_name='Status antes da ausÃªncia'),
        ),
    ]
