# Generated by Django 6.0.6 on 2026-07-17 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acolhimento', '0017_acolhimento_data_ausente_and_more'),
        ('recepcao', '0008_alter_recepcao_cns'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='acolhimento',
            index=models.Index(fields=['status', 'data_acolhimento'], name='acolh_status_data_idx'),
        ),
        migrations.AddIndex(
            model_name='acolhimento',
            index=models.Index(fields=['data_acolhimento'], name='acolh_data_idx'),
        ),
        migrations.AddIndex(
            model_name='acolhimento',
            index=models.Index(fields=['status', 'data_ausente'], name='acolh_status_aus_idx'),
        ),
        migrations.AddIndex(
            model_name='acolhimento',
            index=models.Index(fields=['ausente_classificacao', 'data_ausente_classificacao'], name='acolh_aus_class_idx'),
        ),
    ]
