# Generated by Django 6.0.6 on 2026-07-08 21:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('medico', '0017_consultamedica_crm_medico'),
    ]

    operations = [
        migrations.CreateModel(
            name='MedicamentoEstoque',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(db_index=True, max_length=180)),
                ('principio_ativo', models.CharField(blank=True, default='', max_length=180)),
                ('apresentacao', models.CharField(blank=True, default='', help_text='Ex: comprimido, ampola, frasco, bolsa, gotas.', max_length=180)),
                ('concentracao', models.CharField(blank=True, default='', help_text='Ex: 500 mg, 1 g/2 ml, 0,9%.', max_length=120)),
                ('unidade_medida', models.CharField(blank=True, default='unidade', max_length=50)),
                ('estoque_atual', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('estoque_minimo', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('localizacao', models.CharField(blank=True, default='', help_text='Ex: armário, prateleira ou geladeira.', max_length=120)),
                ('ativo', models.BooleanField(default=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Medicamento em Estoque',
                'verbose_name_plural': 'Medicamentos em Estoque',
                'ordering': ['nome', 'apresentacao', 'concentracao'],
            },
        ),
        migrations.CreateModel(
            name='MovimentacaoEstoque',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('ENTRADA', 'Entrada'), ('SAIDA', 'Saída'), ('AJUSTE', 'Ajuste')], max_length=20)),
                ('quantidade', models.DecimalField(decimal_places=2, max_digits=10)),
                ('saldo_anterior', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('saldo_atual', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('lote', models.CharField(blank=True, default='', max_length=120)),
                ('validade', models.DateField(blank=True, null=True)),
                ('origem_destino', models.CharField(blank=True, default='', help_text='Ex: fornecedor, setor, paciente, perda ou inventário.', max_length=180)),
                ('profissional_nome', models.CharField(max_length=150)),
                ('profissional_registro', models.CharField(blank=True, default='', max_length=60)),
                ('observacao', models.TextField(blank=True, default='')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('consulta', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='movimentacoes_farmacia', to='medico.consultamedica')),
                ('medicamento', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='movimentacoes', to='farmacia.medicamentoestoque')),
            ],
            options={
                'verbose_name': 'Movimentação de Estoque',
                'verbose_name_plural': 'Movimentações de Estoque',
                'ordering': ['-criado_em'],
            },
        ),
    ]
