# Generated by Django 6.0.6 on 2026-07-08 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farmacia', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='medicamentoestoque',
            options={'ordering': ['categoria', 'nome', 'apresentacao', 'concentracao'], 'verbose_name': 'Medicamento em Estoque', 'verbose_name_plural': 'Medicamentos em Estoque'},
        ),
        migrations.AddField(
            model_name='medicamentoestoque',
            name='categoria',
            field=models.CharField(choices=[('COMPRIMIDOS', 'MEDICAMENTOS COMPRIMIDOS'), ('INJETAVEIS', 'MEDICAMENTOS INJETÁVEIS'), ('FRASCO_SOLUCAO_XAROPE', 'MEDICAMENTOS FRASCO / SOLUÇÃO E XAROPE'), ('POMADAS_CREMES_GEL', 'POMADAS / CREMES / GEL'), ('PSICOTROPICOS', 'PSICOTRÓPICOS')], db_index=True, default='COMPRIMIDOS', max_length=40),
        ),
    ]
