# Generated by Django 6.0.6 on 2026-07-08 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farmacia', '0002_alter_medicamentoestoque_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicamentoestoque',
            name='metodo_aplicacao',
            field=models.CharField(choices=[('ORAL', 'Oral'), ('SUBLINGUAL', 'Sublingual'), ('ENDOVENOSA', 'Endovenosa / EV'), ('INTRAMUSCULAR', 'Intramuscular / IM'), ('SUBCUTANEA', 'Subcutanea / SC'), ('INALATORIA', 'Inalatoria'), ('TOPICA', 'Topica'), ('OFTALMICA', 'Oftalmica'), ('OTOLOGICA', 'Otologica'), ('NASAL', 'Nasal'), ('RETAL', 'Retal'), ('VAGINAL', 'Vaginal'), ('OUTRA', 'Outra')], db_index=True, default='ORAL', max_length=40, verbose_name='Metodo de aplicacao'),
        ),
    ]
