# Generated by Codex on 2026-07-10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("farmacia", "0003_medicamentoestoque_metodo_aplicacao"),
    ]

    operations = [
        migrations.AlterField(
            model_name="medicamentoestoque",
            name="estoque_atual",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="medicamentoestoque",
            name="estoque_minimo",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="movimentacaoestoque",
            name="quantidade",
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name="movimentacaoestoque",
            name="saldo_anterior",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="movimentacaoestoque",
            name="saldo_atual",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
