# Generated by Codex on 2026-07-12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("farmacia", "0004_quantidades_estoque_inteiras"),
    ]

    operations = [
        migrations.AddField(
            model_name="medicamentoestoque",
            name="lote_atual",
            field=models.CharField(blank=True, default="", max_length=120),
        ),
        migrations.AddField(
            model_name="medicamentoestoque",
            name="validade",
            field=models.DateField(blank=True, null=True),
        ),
    ]
