# Generated by Django 6.0.6 on 2026-07-17 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farmacia', '0005_medicamentoestoque_lote_validade'),
        ('medico', '0019_consultamedica_consulta_data_idx_and_more'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='medicamentoestoque',
            index=models.Index(fields=['ativo', 'categoria', 'nome'], name='med_ativo_cat_nome_idx'),
        ),
        migrations.AddIndex(
            model_name='medicamentoestoque',
            index=models.Index(fields=['ativo', 'validade'], name='med_ativo_valid_idx'),
        ),
        migrations.AddIndex(
            model_name='medicamentoestoque',
            index=models.Index(fields=['categoria', 'metodo_aplicacao'], name='med_cat_metodo_idx'),
        ),
        migrations.AddIndex(
            model_name='movimentacaoestoque',
            index=models.Index(fields=['medicamento', 'criado_em'], name='mov_med_data_idx'),
        ),
        migrations.AddIndex(
            model_name='movimentacaoestoque',
            index=models.Index(fields=['tipo', 'criado_em'], name='mov_tipo_data_idx'),
        ),
    ]
