# Generated by Django 6.0.6 on 2026-07-17 07:38

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tecnologia', '0009_chamado_solicitante_usuario'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='chamadomanutencaoti',
            index=models.Index(fields=['status', 'criado_em'], name='chamado_status_dt_idx'),
        ),
        migrations.AddIndex(
            model_name='chamadomanutencaoti',
            index=models.Index(fields=['solicitante', 'status', 'criado_em'], name='chamado_solic_dt_idx'),
        ),
        migrations.AddIndex(
            model_name='equipamentoti',
            index=models.Index(fields=['ativo', 'ultimo_status'], name='equip_ativo_status_idx'),
        ),
        migrations.AddIndex(
            model_name='equipamentoti',
            index=models.Index(fields=['endereco_rede'], name='equip_endereco_idx'),
        ),
        migrations.AddIndex(
            model_name='equipamentoti',
            index=models.Index(fields=['mac_address'], name='equip_mac_idx'),
        ),
    ]
