# Generated by Django 6.0.6 on 2026-06-28 09:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('acolhimento', '0009_acolhimento_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClassificacaoRisco',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cor', models.CharField(choices=[('VERMELHO', 'Vermelho - Emergência'), ('LARANJA', 'Laranja - Muito Urgente'), ('AMARELO', 'Amarelo - Urgente'), ('VERDE', 'Verde - Pouco Urgente'), ('AZUL', 'Azul - Não Urgente')], max_length=20)),
                ('queixa_principal', models.TextField()),
                ('peso', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('altura', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True)),
                ('glicemia', models.PositiveIntegerField(blank=True, null=True)),
                ('saturacao', models.PositiveIntegerField(blank=True, null=True)),
                ('observacoes', models.TextField(blank=True)),
                ('data_classificacao', models.DateTimeField(auto_now_add=True)),
                ('acolhimento', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='classificacao', to='acolhimento.acolhimento')),
            ],
        ),
    ]
