# Generated by Django 6.0.6 on 2026-07-04 17:11

import classificacao.models
import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('acolhimento', '0010_alter_acolhimento_options_alter_acolhimento_cpf_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClassificacaoRisco',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_chegada', models.DateField(default=django.utils.timezone.localdate)),
                ('hora_chegada', models.TimeField(default=classificacao.models.hora_atual)),
                ('forma_chegada', models.CharField(choices=[('ESPONTANEA', 'Espontânea'), ('SAMU', 'SAMU'), ('AMBULANCIA', 'Ambulância'), ('BOMBEIROS', 'Bombeiros'), ('TRANSFERENCIA', 'Transferência'), ('OUTROS', 'Outros')], default='ESPONTANEA', max_length=30)),
                ('usuario_responsavel', models.CharField(default='Sistema', max_length=150)),
                ('queixa_principal', models.TextField(verbose_name='Descrição do sintoma')),
                ('tempo_inicio_sintoma', models.CharField(default='Não informado', max_length=100)),
                ('escala_dor', models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)])),
                ('doenca_pre_existente', models.TextField(blank=True)),
                ('alergia', models.TextField(blank=True)),
                ('uso_medicamento', models.TextField(blank=True)),
                ('possivel_gravidez', models.CharField(blank=True, choices=[('NAO_SE_APLICA', 'Não se aplica'), ('NAO', 'Não'), ('SIM', 'Sim'), ('IGNORADO', 'Ignorado')], max_length=20, null=True)),
                ('deficiencia', models.CharField(blank=True, max_length=200)),
                ('cor', models.CharField(choices=[('VERMELHO', 'Vermelho - Emergência'), ('LARANJA', 'Laranja - Muito Urgente'), ('AMARELO', 'Amarelo - Urgente'), ('VERDE', 'Verde - Pouco Urgente'), ('AZUL', 'Azul - Não Urgente')], max_length=20)),
                ('saturacao', models.PositiveIntegerField(default=98, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('glicemia', models.PositiveIntegerField(blank=True, null=True)),
                ('peso', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('altura', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True)),
                ('observacoes', models.TextField(blank=True)),
                ('data_classificacao', models.DateTimeField(auto_now_add=True)),
                ('acolhimento', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='classificacao', to='acolhimento.acolhimento')),
            ],
            options={
                'verbose_name': 'Classificação de Risco',
                'verbose_name_plural': 'Classificações de Risco',
                'ordering': ['-data_classificacao'],
            },
        ),
    ]
