# Generated by Django 6.0.6 on 2026-07-04 17:13

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classificacao', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='classificacaorisco',
            name='saturacao',
        ),
        migrations.AlterField(
            model_name='classificacaorisco',
            name='data_chegada',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
