# Generated by Django 6.0.6 on 2026-07-05 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classificacao', '0002_remove_classificacaorisco_saturacao_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classificacaorisco',
            name='forma_chegada',
            field=models.CharField(choices=[('ESPONTANEA', 'Espontânea'), ('SAMU', 'SAMU'), ('AMBULANCIA', 'Ambulância'), ('BOMBEIROS', 'Corpo de Bombeiros'), ('TRANSFERENCIA', 'Transferência'), ('POLICIA_MILITAR', 'Polícia Militar'), ('POLICIA_CIVIL', 'Polícia Civil'), ('POLICIA_FEDERAL', 'Polícia Federal'), ('POLICIA_RODOVIARIA_FEDERAL', 'Polícia Rodoviária Federal'), ('POLICIA_PENAL', 'Polícia Penal'), ('POLICIA_CIENTIFICA', 'Polícia Científica / Técnica'), ('GUARDA_MUNICIPAL', 'Guarda Municipal'), ('FORCA_NACIONAL', 'Força Nacional'), ('EXERCITO', 'Exército Brasileiro'), ('MARINHA', 'Marinha do Brasil'), ('AERONAUTICA', 'Força Aérea Brasileira'), ('OUTROS', 'Outros')], default='ESPONTANEA', max_length=30),
        ),
    ]
