# Generated by Django 6.0.6 on 2026-07-17 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acolhimento', '0018_acolhimento_acolh_status_data_idx_and_more'),
        ('classificacao', '0003_alter_classificacaorisco_forma_chegada'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='classificacaorisco',
            index=models.Index(fields=['data_classificacao'], name='classif_data_idx'),
        ),
        migrations.AddIndex(
            model_name='classificacaorisco',
            index=models.Index(fields=['usuario_responsavel', 'data_classificacao'], name='classif_usuario_dt_idx'),
        ),
    ]
